const dummydata = [
  {
    bootcampId: 1,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 2,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 3,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 4,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 5,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 6,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 7,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 8,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 9,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 10,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 11,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 12,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 13,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 14,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 15,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 16,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 17,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 18,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 19,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 20,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 21,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 22,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 23,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 24,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 25,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 26,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '백엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
  {
    bootcampId: 27,
    title: '코드스테이츠',
    beginRegisterDate: '2022 - 11 - 25',
    finalRegisterDate: '2022 - 11 - 30',
    process: '프론트엔드',
    totalCost: '무료(국비지원)',
    onOff: '온라인',
  },
];
export default dummydata;
